//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_absence
    {
        public System.DateTime AbsDate { get; set; }
        public int stdId { get; set; }
        public Nullable<bool> status { get; set; }
    
        public virtual student student { get; set; }
    }
}
